type = "webpack"
account_id = "ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""
name = "reddit-bot-dev"
webpack_config = "webpack.config.js"

[env.production]
name = "reddit-bot"
webpack_config = "webpack.production.js"
