name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Prepare Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - name: Install Node packages
        run: npm ci
      - name: Create wrangler.toml
        run: |
          sed "s/ACCOUNT_ID/$ACCOUNT_ID/" wrangler.example.toml > wrangler.toml
        env:
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT }}
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          environment: "production"
